# Load data

In [2]:
import pandas as pd

In [58]:
df = pd.read_csv('../data/jobindex_2021.csv')

In [64]:
# share BEFORE dropping NA titles
print(df.shape)

# lower case titles
df['title'] = df['title'].str.lower()

# remove NAN job titles
# df_nona = df.dropna(subset=['title'])

# shape AFTER dropping NA
# df_nona.shape

(4820088, 13)

# Select job titles (exact match)

The select job titles are: 
- Kok
- Journalist
- Læge
- Elektriker
- Sygeplejerske
- Ejendomsmægler



PS: Excluded IT-sikkerhead because it's a category.

In [68]:
# Example kok & journalist

# df.head()

df[df.title.str.contains('kok', na=False)]

# df_nona

,id,title,company,location,description,source,date,company_rating,type,description_img,company_rating_amount,ratings_link,link
89,90,kragerup gods søger 2 udlærte kokke,Kragerup Gods,Ruds Vedby,Vi tilbyder et spændende og alsidigt job m...,Jobcenter,2021-03-02,NaN,unpaid,NaN,NaN,NaN,/bruger/dine-job/r9420351/gem
655,656,erfaren kok/cater søges,SCHILLERHUSET ApS,København N,Schillerhuset er en full-service kontorhot...,Jobcenter,2021-02-23,NaN,unpaid,NaN,NaN,NaN,/bruger/dine-job/r9403253/gem
785,786,flyvefisken risskov søger faglært kok,FLYVEFISKEN RISSKOV ApS,Risskov,Flyvefisken Risskov er en delikatessebutik...,Jobcenter,2021-02-22,NaN,unpaid,NaN,NaN,NaN,/bruger/dine-job/r9402225/gem
1018,1019,kok søges,Restaurationsselskabet af 13. August 2015 ApS,Aalborg,Vores restaurant i Aalborg har rygende tra...,Restaurationsselskabet af 13. August 2015 ApS,2021-02-19,NaN,unpaid,NaN,NaN,NaN,/bruger/dine-job/r9397944/gem
1271,1272,kok søges til restaurant nordstjernen blokhus,Restaurant Nordstjernen Blokhus ApS,Blokhus,"Restaurant Nordstjernen, har d. 1/10-2020 ...",Jobcenter,2021-02-18,NaN,unpaid,NaN,NaN,NaN,/bruger/dine-job/r9396643/gem
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4819750,4820846,kok til hotel koldingfjord,Hotel Koldingfjord,Kolding,Er du faguddannet kok med interesse i din ...,Jobzonen,2007-01-08,NaN,unpaid,NaN,NaN,NaN,/bruger/dine-job/r1578489/gem
4819751,4820847,kok søges til hotel randers,Hotel Randers,Region Midtjylland,Grundet travlhed søger Hotel Randers en ko...,Jobzonen,2007-01-08,NaN,unpaid,NaN,NaN,NaN,/bruger/dine-job/r1578847/gem
4819903,4820999,slagtersvend/kok,Lokal-Aviserne Fjordbyerne & Slotsbyerne,Helsinge,Att: Se kontaktpersonen i jobannoncen.,Jobselect,2007-01-08,NaN,unpaid,NaN,NaN,NaN,/bruger/dine-job/r1579508/gem
4819913,4821009,kok eller køkkenassistent søges,MEDIREST DIN PRIVATE KOK,København V,Løn i følge nærmere aftale.,AF-Sjaelland,2007-01-08,NaN,unpaid,NaN,NaN,NaN,/bruger/dine-job/r1577836/gem
4820020,4821116,selvstændig kok søges,Organic Catering & Consulting v/Tina Kragh Gade,København V,Organic Catering er en nyopstartet virksom...,AF-Sjaelland,2007-01-08,NaN,unpaid,NaN,NaN,NaN,/bruger/dine-job/r1577860/gem

# Normalize

# Display evolution over time